apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: 323928186444.dkr.ecr.us-east-1.amazonaws.com/app-backend-prod
  newName: 323928186444.dkr.ecr.us-east-1.amazonaws.com/app-backend-prod
  newTag: 4a0b8ab3e8d525ce28c3b913d8ff25062a25ce70
- name: 323928186444.dkr.ecr.us-east-1.amazonaws.com/app-frontend-prod
  newName: 323928186444.dkr.ecr.us-east-1.amazonaws.com/app-frontend-prod
  newTag: 4a0b8ab3e8d525ce28c3b913d8ff25062a25ce70
