apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: youcode-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youcode-frontend
  template:
    metadata:
      labels:
        app: youcode-frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
      - name: frontend
        image: 323928186444.dkr.ecr.us-east-1.amazonaws.com/app-frontend-prod:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "/api"
  strategy:
    blueGreen:
      activeService: youcode-frontend
      previewService: youcode-frontend-preview
      autoPromotionEnabled: false
---
apiVersion: v1
kind: Service
metadata:
  name: youcode-frontend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: youcode-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: youcode-frontend-preview
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: youcode-frontend
