apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youcode-ingress
  namespace: youcode-prod
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: youcode-backend-prod
            port:
              number: 8081
      - path: /
        pathType: Prefix
        backend:
          service:
            name: youcode-frontend-prod
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: youcode-backend-prod
  namespace: youcode-prod
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: youcode-backend
    env: prod
    color: blue # This will be swapped by the pipeline
---
apiVersion: v1
kind: Service
metadata:
  name: youcode-frontend-prod
  namespace: youcode-prod
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: youcode-frontend
    env: prod
    color: blue # This will be swapped by the pipeline
